openapi: 3.1.0
info:
  title: HRMS Elite API v1
  version: "1.0.0"
  description: |
    OpenAPI specification for HRMS Elite API version 1.
    Includes authentication, document management and user endpoints.
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/v1/auth/login:
    post:
      tags: [Authentication]
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
                companyId:
                  type: string
      responses:
        '200':
          description: Logged in successfully
  /api/v1/auth/logout:
    post:
      tags: [Authentication]
      summary: User logout
      security:
        - sessionAuth: []
        - csrfToken: []
      responses:
        '200':
          description: Logged out successfully
  /api/v1/auth/user:
    get:
      tags: [Authentication]
      summary: Get current user
      security:
        - sessionAuth: []
        - csrfToken: []
      responses:
        '200':
          description: Current user returned
  /api/v1/documents:
    get:
      tags: [Documents]
      summary: List documents
      security:
        - sessionAuth: []
        - csrfToken: []
      responses:
        '200':
          description: Array of documents
    post:
      tags: [Documents]
      summary: Create document metadata
      security:
        - sessionAuth: []
        - csrfToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                type:
                  type: string
      responses:
        '201':
          description: Document created
  /api/v1/documents/{id}:
    get:
      tags: [Documents]
      summary: Get document by ID
      security:
        - sessionAuth: []
        - csrfToken: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Document details
    delete:
      tags: [Documents]
      summary: Delete document
      security:
        - sessionAuth: []
        - csrfToken: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Document deleted
  /api/v1/documents/upload:
    post:
      tags: [Documents]
      summary: Upload document file
      security:
        - sessionAuth: []
        - csrfToken: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: File uploaded
  /api/v1/employees:
    get:
      tags: [Users]
      summary: List employees
      security:
        - sessionAuth: []
        - csrfToken: []
      responses:
        '200':
          description: Array of employees
    post:
      tags: [Users]
      summary: Create employee
      security:
        - sessionAuth: []
        - csrfToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [firstName, lastName, email]
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
      responses:
        '201':
          description: Employee created
  /api/v1/employees/{id}:
    get:
      tags: [Users]
      summary: Get employee by ID
      security:
        - sessionAuth: []
        - csrfToken: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employee details
components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: connect.sid
      description: Session authentication cookie
    csrfToken:
      type: apiKey
      in: header
      name: X-CSRF-Token
      description: CSRF protection token
