global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # HRMS Elite Application - Staging
  - job_name: 'hrms-elite-app-staging'
    static_configs:
      - targets: ['hrms-app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Nginx - Staging
  - job_name: 'nginx-staging'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 60s

  # Redis - Staging
  - job_name: 'redis-staging'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s

  # Node Exporter (system metrics) - Staging
  - job_name: 'node-exporter-staging'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 60s 