
// Auto-generated comprehensive routes with ALL real data
import { Express } from "express";

const allCompaniesData = [
  {
    "id": "1",
    "name": "شركة الاتحاد الخليجي للأقمشة",
    "employeeCount": 51,
    "licenseCount": 1,
    "documentCount": 4,
    "requestCount": 3,
    "type": "textile",
    "status": "active"
  },
  {
    "id": "2",
    "name": "شركة النيل الأزرق للمجوهرات",
    "employeeCount": 57,
    "licenseCount": 5,
    "documentCount": 7,
    "requestCount": 1,
    "type": "jewelry",
    "status": "active"
  },
  {
    "id": "3",
    "name": "شركة قمة النيل للذهب",
    "employeeCount": 38,
    "licenseCount": 1,
    "documentCount": 5,
    "requestCount": 1,
    "type": "jewelry",
    "status": "active"
  },
  {
    "id": "4",
    "name": "شركة محمد أحمد إبراهيم",
    "employeeCount": 52,
    "licenseCount": 1,
    "documentCount": 4,
    "requestCount": 1,
    "type": "textile",
    "status": "active"
  },
  {
    "id": "5",
    "name": "شركة ميلانو للأزياء",
    "employeeCount": 75,
    "licenseCount": 1,
    "documentCount": 5,
    "requestCount": 0,
    "type": "textile",
    "status": "active"
  }
];

const allEmployeesData = [
  {
    "id": "emp-1-1",
    "name": "1",
    "position": "260092101255",
    "department": "حسين علي محمدي",
    "nationality": "شريك",
    "civilId": "14/01/2025",
    "passport": "13/01/2027",
    "residencyNumber": "شرك ",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-2",
    "name": "2",
    "position": "279022804617",
    "department": "هوجافا رجب علي",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "27/09/2023",
    "passport": "26/09/2026",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-3",
    "name": "3",
    "position": "291092201207",
    "department": "رامين حسنعلي محمدي",
    "nationality": "مسئول مشتريات",
    "civilId": "15/10/2023",
    "passport": "14/10/2026",
    "residencyNumber": "1000",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-4",
    "name": "4",
    "position": "285121502914",
    "department": "هاني مختار كامل سدراك",
    "nationality": "سائق مركبه خفيفه",
    "civilId": "44997",
    "passport": "45700",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-5",
    "name": "5",
    "position": "278042801259",
    "department": "اسماعيل نوروز اسماعيلى",
    "nationality": "مسئول معرض",
    "civilId": "26/12/2023",
    "passport": "25/12/2026",
    "residencyNumber": "750",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-6",
    "name": "6",
    "position": "290013002214",
    "department": "خليل نوروز اسماعيلى",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "14/10/2024",
    "passport": "13/10/2025",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-7",
    "name": "7",
    "position": "272120601352",
    "department": "نواز الله درويش علي محمدي",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "17/10/2024",
    "passport": "16/10/2025",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-8",
    "name": "8",
    "position": "294111202322",
    "department": "جعفر مستقيم",
    "nationality": "بائع أقمشة",
    "civilId": "28/12/2024",
    "passport": "27/12/2025",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-9",
    "name": "9",
    "position": "274031504066",
    "department": "جورج وجيه سدره بولس",
    "nationality": "مدير مالي",
    "civilId": "45966",
    "passport": "46665",
    "residencyNumber": "1500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-10",
    "name": "10",
    "position": "263051700722",
    "department": "سيد صالح محمد صالحى",
    "nationality": "بائع أقمشة",
    "civilId": "18/05/2025",
    "passport": "17/05/2027",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-11",
    "name": "1",
    "position": "290121501133",
    "department": "نسترن حسين على محمدى",
    "nationality": "مصمم أزياء",
    "civilId": "45208",
    "passport": "46274",
    "residencyNumber": "1000",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-12",
    "name": "2",
    "position": "279031102414",
    "department": "بهزاد محمدرضى سلجوقى",
    "nationality": "مسئول معرض",
    "civilId": "15/10/2023",
    "passport": "14/10/2026",
    "residencyNumber": "550",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-13",
    "name": "3",
    "position": "276103102832",
    "department": "ابرام فوزى لبيب جرجس",
    "nationality": "مخلص معاملات",
    "civilId": "45149",
    "passport": "45849",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-14",
    "name": "4",
    "position": "278061020749",
    "department": "فيصل اوكيل محمد كوتي",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "17/08/2024",
    "passport": "16/08/2025",
    "residencyNumber": "100",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-15",
    "name": "5",
    "position": "269051016629",
    "department": "سرينفاسان كودومدان شانموجان",
    "nationality": "بائع أقمشة",
    "civilId": "25/03/2025",
    "passport": "24/03/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-16",
    "name": "6",
    "position": "266051202858",
    "department": "عبدالجبار اوناراكاتيل محمد اوني",
    "nationality": "بائع أقمشة",
    "civilId": "25/03/2025",
    "passport": "24/03/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-17",
    "name": "7",
    "position": "284102701884",
    "department": "عبدالكريم جمشيد جمالى",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45812",
    "passport": "46146",
    "residencyNumber": "650",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-18",
    "name": "1",
    "position": "269013003536",
    "department": "محمد شهيدالله محمد نورالهدى",
    "nationality": "بائع",
    "civilId": "45385",
    "passport": "45719",
    "residencyNumber": "تغيب ",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-19",
    "name": "2",
    "position": "291081705151",
    "department": "ماسيد علمكازا ابوالكلام",
    "nationality": "بائع أقمشة",
    "civilId": "45299",
    "passport": "31/07/2025",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-20",
    "name": "3",
    "position": "262072401655",
    "department": "مسعود محمد رفيع يادكارى",
    "nationality": "بائع أقمشة",
    "civilId": "20/08/2024",
    "passport": "19/08/2025",
    "residencyNumber": "400",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-21",
    "name": "4",
    "position": "265030102132",
    "department": "جميل صبحى حبيب فرج",
    "nationality": "بائع أقمشة",
    "civilId": "25/08/2024",
    "passport": "24/08/2025",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-22",
    "name": "5",
    "position": "292121102086",
    "department": "عادل حسين زاكير حسين",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "13/10/2024",
    "passport": "46366",
    "residencyNumber": "120",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-23",
    "name": "6",
    "position": "292021103014",
    "department": "ازهار احمد",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45423",
    "passport": "45758",
    "residencyNumber": "120",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-24",
    "name": "7",
    "position": "284091502475",
    "department": "شهرام محمد نور احمدى",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45809",
    "passport": "46143",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-25",
    "name": "8",
    "position": "262090802348",
    "department": "مجدي عبدالحميد ابراهيم شاهين",
    "nationality": "محاسب عام",
    "civilId": "45932",
    "passport": "46267",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-26",
    "name": "9",
    "position": "275101804465",
    "department": "براتاب سينجه سوهان",
    "nationality": "بائع أقمشة",
    "civilId": "45811",
    "passport": "46510",
    "residencyNumber": "250",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-27",
    "name": "10",
    "position": "297091303575",
    "department": "جيثين راج",
    "nationality": "بائع أقمشة",
    "civilId": "30/03/2025",
    "passport": "29/03/2026",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-28",
    "name": "11",
    "position": "302041302199",
    "department": "ساجد حسين قريشي شاكر حسين قريشي",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "14/04/2025",
    "passport": "13/04/2026",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-29",
    "name": "12",
    "position": "299071505347",
    "department": "ام دي تنفير ام دي اسلام مياه احمد",
    "nationality": "بائع أقمشة",
    "civilId": "19/04/2025",
    "passport": "18/04/2026",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-30",
    "name": "1",
    "position": "283033005548",
    "department": "نادى فهيم انيس رزق",
    "nationality": "بائع",
    "civilId": "45271",
    "passport": "45972",
    "residencyNumber": "400",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-31",
    "name": "2",
    "position": "287092502614",
    "department": "افرايم زكريا عوض مقار",
    "nationality": "بائع أقمشة",
    "civilId": "45963",
    "passport": "46297",
    "residencyNumber": "400",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-32",
    "name": "3",
    "position": "279090304358",
    "department": "امر اله نور اله اسمعيلي",
    "nationality": "محصل كمبيالات",
    "civilId": "16/02/2025",
    "passport": "15/02/2026",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-33",
    "name": "4",
    "position": "290021505831",
    "department": "شوبهام سيسوديا شانكار لال سيسوديا",
    "nationality": "بائع أقمشة",
    "civilId": "26/03/2025",
    "passport": "25/03/2026",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-34",
    "name": "5",
    "position": "285031608248",
    "department": "جيتيندرا يادف",
    "nationality": "بائع أقمشة",
    "civilId": "45752",
    "passport": "46086",
    "residencyNumber": "120",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-35",
    "name": "1",
    "position": "296071901928",
    "department": "سلمان راتهود",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45300",
    "passport": "31/08/2025",
    "residencyNumber": "120",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-36",
    "name": "2",
    "position": "300060103399",
    "department": "شيخ فرحان شيخ اسحاق شيخ",
    "nationality": "خياط عبايات نسائية",
    "civilId": "45637",
    "passport": "45972",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-37",
    "name": "3",
    "position": "280020112228",
    "department": "مانجور علم كازى عبدالكريم",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45993",
    "passport": "46328",
    "residencyNumber": "250",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-38",
    "name": "4",
    "position": "278030111154",
    "department": "امين سكندر علي",
    "nationality": "بائع أقمشة",
    "civilId": "45935",
    "passport": "46270",
    "residencyNumber": "100",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-39",
    "name": "1",
    "position": "295010108454",
    "department": "محمود يونس عوض",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "25/07/2024",
    "passport": "24/07/2025",
    "residencyNumber": "450",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-40",
    "name": "2",
    "position": "268061605254",
    "department": "قاسم محسن كعبي تبار",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "23/11/2024",
    "passport": "22/11/2025",
    "residencyNumber": "600",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-41",
    "name": "3",
    "position": "291020403838",
    "department": "اسماعيل خسرو هرتياش",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45811",
    "passport": "46145",
    "residencyNumber": "600",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-42",
    "name": "1",
    "position": "284092203565",
    "department": "مدحت اديب صموئيل بباوي",
    "nationality": "بائع",
    "civilId": "24/12/2023",
    "passport": "23/12/2025",
    "residencyNumber": "350",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-43",
    "name": "2",
    "position": "293010308297",
    "department": "مصطفى حسين عبيد حسين",
    "nationality": "بائع أقمشة",
    "civilId": "27/06/2024",
    "passport": "26/06/2025",
    "residencyNumber": "600",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-44",
    "name": "3",
    "position": "294102900014",
    "department": "حسام عبدالعزيز عبدالله الهى",
    "nationality": "مندوب مشتريات",
    "civilId": "25/09/2024",
    "passport": "24/09/2025",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-45",
    "name": "4",
    "position": "281080508026",
    "department": "ريمون ميلاد توفيق عبده",
    "nationality": "بائع أقمشة",
    "civilId": "45933",
    "passport": "46268",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-46",
    "name": "5",
    "position": "269111500245",
    "department": "نادر على فرح بخش",
    "nationality": "مخلص معاملات",
    "civilId": "27/03/2025",
    "passport": "26/03/2026",
    "residencyNumber": "650",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-47",
    "name": "6",
    "position": "261092500832",
    "department": "محمد عبد الله غلامى",
    "nationality": "بائع أقمشة",
    "civilId": "18/05/2025",
    "passport": "17/05/2026",
    "residencyNumber": "350",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-48",
    "name": "7",
    "position": "276020703851",
    "department": "شاه علم بادى العلم",
    "nationality": "بائع أقمشة",
    "civilId": "27/05/2025",
    "passport": "26/05/2026",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-49",
    "name": "1",
    "position": "287061204606",
    "department": "دهيراج كومار ياداف",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "17/09/2024",
    "passport": "16/09/2025",
    "residencyNumber": "250",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-50",
    "name": "2",
    "position": "278062803024",
    "department": "ابوحنيف مالا بوكس برامانيك",
    "nationality": "خياط ملابس نسائية",
    "civilId": "24/10/2024",
    "passport": "23/10/2025",
    "residencyNumber": "100",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-1-51",
    "name": "3",
    "position": "301101502885",
    "department": "عزيجول هوك نور الاسلام",
    "nationality": "بائع أقمشة",
    "civilId": "21/01/2025",
    "passport": "20/01/2026",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@gulf-union.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "fileSource": "اسماء عمال شركة الاتحاد الخليجي جميع التراخيص (2).xlsx"
  },
  {
    "id": "emp-2-1",
    "name": "1",
    "position": "299041502081",
    "department": "محمد علي محمد بناهي",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "28/04/2024",
    "passport": "27/04/2026",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-2",
    "name": "2",
    "position": "295050401137",
    "department": "محمد جواد حشمت الله سليماني",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45329",
    "passport": "45664",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-3",
    "name": "3",
    "position": "285010606374",
    "department": "عبدالصبور مرغني نور غلاب",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "17/10/2024",
    "passport": "16/10/2025",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-4",
    "name": "4",
    "position": "263080501829",
    "department": "ماهيبال بانجال شانكار لال بانجال",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "14/12/2024",
    "passport": "13/12/2025",
    "residencyNumber": "80",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-5",
    "name": "5",
    "position": "265123002026",
    "department": "محمد شعيب عبد الرحيم بايدار",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45809",
    "passport": "46143",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-6",
    "name": "6",
    "position": "285092302058",
    "department": "جاسم عبدالكريم نيكو",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "24/02/2025",
    "passport": "23/02/2026",
    "residencyNumber": "",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-7",
    "name": "1",
    "position": "292042401264",
    "department": "محمد مفلح الرفاعى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45298",
    "passport": "30/06/2025",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-8",
    "name": "2",
    "position": "274072303236",
    "department": "عمران عبدالرحمن حاج حمد",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "24/08/2024",
    "passport": "23/08/2025",
    "residencyNumber": "600",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-9",
    "name": "3",
    "position": "293123105381",
    "department": "سهند ارسلان نوروزي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45748",
    "passport": "46082",
    "residencyNumber": "650",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-10",
    "name": "4",
    "position": "298071302078",
    "department": "مصطفى بابوجيوالا قطبالدين",
    "nationality": "محاسب تكاليف",
    "civilId": "20/03/2025",
    "passport": "19/03/2026",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-11",
    "name": "5",
    "position": "276042101819",
    "department": "محمد نبي محمد رضا صادقي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "26/03/2025",
    "passport": "25/03/2026",
    "residencyNumber": "900",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-12",
    "name": "1",
    "position": "303060103384",
    "department": "عمر مذيب الجباوي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "23/10/2024",
    "passport": "22/10/2025",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-13",
    "name": "2",
    "position": "289081501308",
    "department": "جعفر عبد الكريم جياد حمدى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "16/04/2025",
    "passport": "15/04/2026",
    "residencyNumber": "450",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-14",
    "name": "3",
    "position": "283082900688",
    "department": "محمود فخرى عبد العزيز",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "28/04/2025",
    "passport": "27/04/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-15",
    "name": "4",
    "position": "297010103767",
    "department": "محمد امين خالد الزعبى",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45966",
    "passport": "46300",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-16",
    "name": "5",
    "position": "298122001735",
    "department": "حسن نورالدين الغياض",
    "nationality": "سائق / سيارة خصوصي",
    "civilId": "45966",
    "passport": "46300",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-17",
    "name": "6",
    "position": "295061101826",
    "department": "نصر عبدالكريم الرفاعى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "20/05/2025",
    "passport": "19/05/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-18",
    "name": "1",
    "position": "273071901299",
    "department": "عايد محمد الحاج على",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "23/06/2024",
    "passport": "22/06/2025",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-19",
    "name": "2",
    "position": "282012903643",
    "department": "صدر الله مراد افتابي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45576",
    "passport": "45911",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-20",
    "name": "3",
    "position": "270062002263",
    "department": "محمد طاهر بايدار",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "23/02/2025",
    "passport": "22/02/2026",
    "residencyNumber": "750",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-21",
    "name": "4",
    "position": "296112401795",
    "department": "على صباح حسني زاده",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "26/03/2025",
    "passport": "25/03/2026",
    "residencyNumber": "600",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-22",
    "name": "1",
    "position": "296060600556",
    "department": "أحمد سليمان أحمد توانا",
    "nationality": "مندوب عام",
    "civilId": "22/09/2023",
    "passport": "21/09/2026",
    "residencyNumber": "1000",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-23",
    "name": "2",
    "position": "292111704147",
    "department": "فريد محمد رضا صادقي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "17/09/2024",
    "passport": "16/09/2025",
    "residencyNumber": "400",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-24",
    "name": "3",
    "position": "299121901832",
    "department": "اسماعيل محمد رضا ايزدى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45994",
    "passport": "46329",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-25",
    "name": "4",
    "position": "289072602094",
    "department": "عمران ابراهيم ابراهيم بور",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "27/03/2025",
    "passport": "26/03/2027",
    "residencyNumber": "650",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-26",
    "name": "5",
    "position": "296010301961",
    "department": "مهدى على عباس سرايدارى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45966",
    "passport": "46300",
    "residencyNumber": "650",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-27",
    "name": "6",
    "position": "",
    "department": "",
    "nationality": "",
    "civilId": "",
    "passport": "",
    "residencyNumber": "",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-28",
    "name": "1",
    "position": "287041302137",
    "department": "مهدى جبار خلف عبيات",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "29/01/2025",
    "passport": "28/01/2026",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-29",
    "name": "2",
    "position": "258101900487",
    "department": "على اصغر محمد على طوسى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "15/02/2025",
    "passport": "14/02/2026",
    "residencyNumber": "450",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-30",
    "name": "1",
    "position": "301081600153",
    "department": "محسن سليمان توانا",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "29/03/2025",
    "passport": "28/03/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-31",
    "name": "2",
    "position": "268060601745",
    "department": "ايت الله محمد صادق نصري",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "19/04/2025",
    "passport": "18/04/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-32",
    "name": "3",
    "position": "265100901897",
    "department": "محمد غسان محمد فؤاد الدسوقي",
    "nationality": "بائع منتجات حرف يدوية",
    "civilId": "45782",
    "passport": "46117",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-33",
    "name": "1",
    "position": "270051601762",
    "department": "يعقوب محمد صالح قلندرانى",
    "nationality": "بائع ذهب",
    "civilId": "30/06/2022",
    "passport": "29/06/2025",
    "residencyNumber": "400",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-34",
    "name": "2",
    "position": "300060301694",
    "department": "فرحان محمد شريف واحدى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "16/01/2025",
    "passport": "15/01/2026",
    "residencyNumber": "600",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-35",
    "name": "3",
    "position": "262111102122",
    "department": "داريوش عبد الرحيم رحيمي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "24/02/2025",
    "passport": "23/02/2026",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-36",
    "name": "4",
    "position": "264052301808",
    "department": "محمود هاشم حيدرى",
    "nationality": "بائع منتجات حرف يدوية",
    "civilId": "45782",
    "passport": "46117",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-37",
    "name": "5",
    "position": "286072301968",
    "department": "بهنام اسماعيل محمدى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45905",
    "passport": "46239",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-38",
    "name": "1",
    "position": "266090801474",
    "department": "عبد الحميد محمود بايدار",
    "nationality": "صائغ",
    "civilId": "20/06/2023",
    "passport": "19/06/2025",
    "residencyNumber": "750",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-39",
    "name": "2",
    "position": "276082302842",
    "department": "عبدالله محمد صالح قلندراني",
    "nationality": "بائع",
    "civilId": "21/08/2023",
    "passport": "20/08/2025",
    "residencyNumber": "500",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-40",
    "name": "3",
    "position": "295120101982",
    "department": "سوبهانكر كوليي",
    "nationality": "صائغ",
    "civilId": "45414",
    "passport": "46114",
    "residencyNumber": "120",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-41",
    "name": "4",
    "position": "279030309579",
    "department": "كوكان شاندرا روي كوبال",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "13/08/2024",
    "passport": "45999",
    "residencyNumber": "150",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-42",
    "name": "5",
    "position": "275062501807",
    "department": "زيشهام علام ملهى محمد علام ملهى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "45749",
    "passport": "46083",
    "residencyNumber": "260",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-43",
    "name": "6",
    "position": "289031510054",
    "department": "برادوث مايتي",
    "nationality": "عامل كشط معادن",
    "civilId": "45749",
    "passport": "46083",
    "residencyNumber": "120",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-44",
    "name": "7",
    "position": "299090201285",
    "department": "احمد يوسف ابراهيمي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "20/04/2025",
    "passport": "19/04/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-45",
    "name": "8",
    "position": "299090201277",
    "department": "امين يوسف ابراهيمي",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "20/04/2025",
    "passport": "19/04/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-46",
    "name": "9",
    "position": "270062801524",
    "department": "عزت الله محمود خادم زاده",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "20/05/2025",
    "passport": "19/05/2027",
    "residencyNumber": "800",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-47",
    "name": "10",
    "position": "",
    "department": "",
    "nationality": "",
    "civilId": "",
    "passport": "",
    "residencyNumber": "",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-48",
    "name": "1",
    "position": "278092301826",
    "department": "فيصل محمد امين شيخ عبدلى",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "28/02/2024",
    "passport": "27/02/2026",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  },
  {
    "id": "emp-2-49",
    "name": "2",
    "position": "294062301462",
    "department": "محمد جبار خلف عبيات",
    "nationality": "صائغ حلي ذهبية",
    "civilId": "21/10/2024",
    "passport": "20/10/2025",
    "residencyNumber": "300",
    "residencyExpiry": "",
    "contractNumber": "",
    "workPermitNumber": "",
    "joinDate": "",
    "basicSalary": 0,
    "allowances": 0,
    "totalSalary": 0,
    "bankAccount": "",
    "iban": "",
    "emergencyContact": "",
    "address": "",
    "email": "employee@blue-nile.com",
    "phone": "",
    "status": "active",
    "notes": "",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "fileSource": "اسماء عمال شركة النيل الازرق جميع التراخيص جورج.xlsx"
  }
];

const allLicensesData = [
  {
    "id": "doc-1753697814787-nciw7",
    "name": "ترخيص الاتحاد الخليجي للاقمشة 2023.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص الاتحاد الخليجي للاقمشة 2023.pdf",
    "uploadDate": "2025-07-28T10:16:54.787Z",
    "size": 508546,
    "type": "license",
    "category": "general",
    "status": "expired",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "licenseNumber": "2023",
    "issueDate": "2023-01-01",
    "expiryDate": "2024-12-31",
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814787-jedmc",
    "name": "ترخيص النيل الازرق الرئيسي مباركية.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص النيل الازرق الرئيسي مباركية.pdf",
    "uploadDate": "2025-07-28T10:16:54.787Z",
    "size": 593639,
    "type": "license",
    "category": "general",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814788-2z4df",
    "name": "ترخيص النيل الازرق محل 3 رامين.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص النيل الازرق محل 3 رامين.pdf",
    "uploadDate": "2025-07-28T10:16:54.788Z",
    "size": 534596,
    "type": "license",
    "category": "general",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814791-erh1h",
    "name": "ترخيص شركة النيل الازرق جهراء 16 توافق 24.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص شركة النيل الازرق جهراء 16 توافق 24.pdf",
    "uploadDate": "2025-07-28T10:16:54.791Z",
    "size": 589326,
    "type": "license",
    "category": "general",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814792-htb6p",
    "name": "ترخيص شركة النيل الازرق للمجوهرات 2-3 فحيحيل.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص شركة النيل الازرق للمجوهرات 2-3 فحيحيل.pdf",
    "uploadDate": "2025-07-28T10:16:54.792Z",
    "size": 591059,
    "type": "license",
    "category": "jewelry",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [
      "مجوهرات"
    ],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814794-xcs7w",
    "name": "ترخيص مكتب النيل الازرق فحيحيل.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص مكتب النيل الازرق فحيحيل.pdf",
    "uploadDate": "2025-07-28T10:16:54.794Z",
    "size": 593712,
    "type": "license",
    "category": "general",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814793-zener",
    "name": "ترخيص قمة النيل.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص قمة النيل.pdf",
    "uploadDate": "2025-07-28T10:16:54.793Z",
    "size": 532941,
    "type": "license",
    "category": "general",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814792-e0ssr",
    "name": "ترخيص شركة محمد احمد ابراهيم 2023.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص شركة محمد احمد ابراهيم 2023.pdf",
    "uploadDate": "2025-07-28T10:16:54.792Z",
    "size": 591047,
    "type": "license",
    "category": "general",
    "status": "expired",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "4",
    "companyName": "شركة محمد أحمد إبراهيم",
    "licenseNumber": "2023",
    "issueDate": "2023-01-01",
    "expiryDate": "2024-12-31",
    "authority": "الجهة المختصة"
  },
  {
    "id": "doc-1753697814790-f2a8n",
    "name": "ترخيص خياط ليزا فاشن ميلانو.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ترخيص خياط ليزا فاشن ميلانو.pdf",
    "uploadDate": "2025-07-28T10:16:54.790Z",
    "size": 532683,
    "type": "license",
    "category": "textiles",
    "status": "active",
    "description": "رخصة تجارية أو صناعية للعمل",
    "tags": [],
    "companyId": "5",
    "companyName": "شركة ميلانو للأزياء",
    "licenseNumber": "غير محدد",
    "issueDate": null,
    "expiryDate": null,
    "authority": "الجهة المختصة"
  }
];

const allDocumentsData = [
  {
    "id": "doc-1753697814663-qh0bf",
    "name": "استيراد الاتحاد   2025.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/استيراد الاتحاد   2025.pdf",
    "uploadDate": "2025-07-28T10:16:54.663Z",
    "size": 212270,
    "type": "import_permit",
    "category": "general",
    "status": "active",
    "description": "تصريح استيراد البضائع",
    "tags": [
      "استيراد"
    ],
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة"
  },
  {
    "id": "doc-1753697814785-8ngiq",
    "name": "الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "uploadDate": "2025-07-28T10:16:54.785Z",
    "type": "general",
    "category": "shared",
    "description": "مستند عام مشترك",
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة"
  },
  {
    "id": "doc-1753697814799-39su6",
    "name": "عقد تاسيس الاتحاد الخليجي (2).pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/عقد تاسيس الاتحاد الخليجي (2).pdf",
    "uploadDate": "2025-07-28T10:16:54.799Z",
    "size": 10278806,
    "type": "contract",
    "category": "general",
    "status": "active",
    "description": "عقد قانوني ملزم",
    "tags": [],
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "contractType": "عقد تجاري",
    "parties": [
      "الاتحاد الخليجي"
    ],
    "value": 2
  },
  {
    "id": "doc-1753697814783-beiun",
    "name": "اعتماد توقيع الاتحاد 20250512.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/اعتماد توقيع الاتحاد 20250512.pdf",
    "uploadDate": "2025-07-28T10:16:54.783Z",
    "size": 491755,
    "type": "certification",
    "category": "general",
    "status": "active",
    "description": "اعتماد رسمي من الجهات المختصة",
    "tags": [],
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة",
    "certificationNumber": "20250512",
    "issuingBody": "الجهة الحكومية المختصة"
  },
  {
    "id": "doc-1753697814664-y670q",
    "name": "استيراد النيل الازرق للمجوهرات 2025.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/استيراد النيل الازرق للمجوهرات 2025.pdf",
    "uploadDate": "2025-07-28T10:16:54.664Z",
    "size": 213427,
    "type": "import_permit",
    "category": "jewelry",
    "status": "active",
    "description": "تصريح استيراد البضائع",
    "tags": [
      "مجوهرات",
      "استيراد"
    ],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات"
  },
  {
    "id": "doc-1753697814785-utvzm",
    "name": "الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "uploadDate": "2025-07-28T10:16:54.785Z",
    "type": "general",
    "category": "shared",
    "description": "مستند عام مشترك",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات"
  },
  {
    "id": "doc-1753697814786-acxdi",
    "name": "بطاقات شركاء النيل الأزرق للمجوهرات.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/بطاقات شركاء النيل الأزرق للمجوهرات.pdf",
    "uploadDate": "2025-07-28T10:16:54.786Z",
    "size": 1492181,
    "type": "identification",
    "category": "jewelry",
    "status": "active",
    "description": "مستند رسمي",
    "tags": [
      "مجوهرات"
    ],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات"
  },
  {
    "id": "doc-1753697814786-1ig8x",
    "name": "ت مصنع  النيل الازرق.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ت مصنع  النيل الازرق.pdf",
    "uploadDate": "2025-07-28T10:16:54.786Z",
    "size": 270950,
    "type": "document",
    "category": "general",
    "status": "active",
    "description": "مستند رسمي",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات"
  },
  {
    "id": "doc-1753697814795-kr0i1",
    "name": "شركة النيل الازرق للمجوهرات نبي ج ج.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/شركة النيل الازرق للمجوهرات نبي ج ج.pdf",
    "uploadDate": "2025-07-28T10:16:54.795Z",
    "size": 590137,
    "type": "document",
    "category": "jewelry",
    "status": "active",
    "description": "مستند رسمي",
    "tags": [
      "مجوهرات"
    ],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات"
  },
  {
    "id": "doc-1753697814799-53pgf",
    "name": "عقد تاسيس النيل الازرق.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/عقد تاسيس النيل الازرق.pdf",
    "uploadDate": "2025-07-28T10:16:54.799Z",
    "size": 6347586,
    "type": "contract",
    "category": "general",
    "status": "active",
    "description": "عقد قانوني ملزم",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "contractType": "عقد تجاري",
    "parties": [],
    "value": 0
  },
  {
    "id": "doc-1753697814782-y9rc0",
    "name": "اعتماد النيل الازرق 20250528.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/اعتماد النيل الازرق 20250528.pdf",
    "uploadDate": "2025-07-28T10:16:54.782Z",
    "size": 685291,
    "type": "certification",
    "category": "general",
    "status": "active",
    "description": "اعتماد رسمي من الجهات المختصة",
    "tags": [],
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات",
    "certificationNumber": "20250528",
    "issuingBody": "الجهة الحكومية المختصة"
  },
  {
    "id": "doc-1753697814665-9gwr8",
    "name": "استيراد قمة النيل  2025.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/استيراد قمة النيل  2025.pdf",
    "uploadDate": "2025-07-28T10:16:54.665Z",
    "size": 212907,
    "type": "import_permit",
    "category": "general",
    "status": "active",
    "description": "تصريح استيراد البضائع",
    "tags": [
      "استيراد"
    ],
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب"
  },
  {
    "id": "doc-1753697814785-s1s9n",
    "name": "الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "uploadDate": "2025-07-28T10:16:54.785Z",
    "type": "general",
    "category": "shared",
    "description": "مستند عام مشترك",
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب"
  },
  {
    "id": "doc-1753697814786-xdtk5",
    "name": "ب م الشركاء قمة النيل (1).pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/ب م الشركاء قمة النيل (1).pdf",
    "uploadDate": "2025-07-28T10:16:54.786Z",
    "size": 785880,
    "type": "document",
    "category": "general",
    "status": "active",
    "description": "مستند رسمي",
    "tags": [],
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب"
  },
  {
    "id": "doc-1753697814800-8apa3",
    "name": "عقد قمة النيل تاسيس وتعديل (4).pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/عقد قمة النيل تاسيس وتعديل (4).pdf",
    "uploadDate": "2025-07-28T10:16:54.800Z",
    "size": 8140712,
    "type": "contract",
    "category": "general",
    "status": "active",
    "description": "عقد قانوني ملزم",
    "tags": [],
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب",
    "contractType": "عقد تجاري",
    "parties": [
      "قمة النيل"
    ],
    "value": 4
  },
  {
    "id": "doc-1753697814785-p3zsl",
    "name": "اعتماد قمة النيل 20250101.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/اعتماد قمة النيل 20250101.pdf",
    "uploadDate": "2025-07-28T10:16:54.785Z",
    "size": 491910,
    "type": "certification",
    "category": "general",
    "status": "active",
    "description": "اعتماد رسمي من الجهات المختصة",
    "tags": [],
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب",
    "certificationNumber": "20250101",
    "issuingBody": "الجهة الحكومية المختصة"
  },
  {
    "id": "doc-1753697814664-4xx35",
    "name": "استيراد شركة محمد احمد 2025.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/استيراد شركة محمد احمد 2025.pdf",
    "uploadDate": "2025-07-28T10:16:54.664Z",
    "size": 213262,
    "type": "import_permit",
    "category": "general",
    "status": "active",
    "description": "تصريح استيراد البضائع",
    "tags": [
      "استيراد"
    ],
    "companyId": "4",
    "companyName": "شركة محمد أحمد إبراهيم"
  },
  {
    "id": "doc-1753697814785-c8eu0",
    "name": "الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "uploadDate": "2025-07-28T10:16:54.785Z",
    "type": "general",
    "category": "shared",
    "description": "مستند عام مشترك",
    "companyId": "4",
    "companyName": "شركة محمد أحمد إبراهيم"
  },
  {
    "id": "doc-1753697814787-cbm52",
    "name": "تاسيس شركة محمد احمد ابراهيم.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/تاسيس شركة محمد احمد ابراهيم.pdf",
    "uploadDate": "2025-07-28T10:16:54.787Z",
    "size": 9713255,
    "type": "document",
    "category": "general",
    "status": "active",
    "description": "مستند رسمي",
    "tags": [],
    "companyId": "4",
    "companyName": "شركة محمد أحمد إبراهيم"
  },
  {
    "id": "doc-1753697814783-guvxg",
    "name": "اعتماد توقيع شركة محمد احمد 2025.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/اعتماد توقيع شركة محمد احمد 2025.pdf",
    "uploadDate": "2025-07-28T10:16:54.783Z",
    "size": 493318,
    "type": "certification",
    "category": "general",
    "status": "active",
    "description": "اعتماد رسمي من الجهات المختصة",
    "tags": [],
    "companyId": "4",
    "companyName": "شركة محمد أحمد إبراهيم",
    "certificationNumber": "doc-1753697814783-r4u69",
    "issuingBody": "الجهة الحكومية المختصة"
  },
  {
    "id": "doc-1753697814785-o7dzd",
    "name": "الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/الهيئة العامة للقوي العاملة عقد عمل جديد.docx",
    "uploadDate": "2025-07-28T10:16:54.785Z",
    "type": "general",
    "category": "shared",
    "description": "مستند عام مشترك",
    "companyId": "5",
    "companyName": "شركة ميلانو للأزياء"
  },
  {
    "id": "doc-1753697814802-38d7c",
    "name": "نرخيص مرمر 2023.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/نرخيص مرمر 2023.pdf",
    "uploadDate": "2025-07-28T10:16:54.802Z",
    "size": 590816,
    "type": "document",
    "category": "general",
    "status": "expired",
    "description": "مستند رسمي",
    "tags": [],
    "companyId": "5",
    "companyName": "شركة ميلانو للأزياء"
  },
  {
    "id": "doc-1753697814802-g51dl",
    "name": "نرخيص ميلانو 2023.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/نرخيص ميلانو 2023.pdf",
    "uploadDate": "2025-07-28T10:16:54.802Z",
    "size": 572408,
    "type": "document",
    "category": "general",
    "status": "expired",
    "description": "مستند رسمي",
    "tags": [],
    "companyId": "5",
    "companyName": "شركة ميلانو للأزياء"
  },
  {
    "id": "doc-1753697814800-hgbkw",
    "name": "عقد تاسيس ميلانو.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/عقد تاسيس ميلانو.pdf",
    "uploadDate": "2025-07-28T10:16:54.800Z",
    "size": 2264860,
    "type": "contract",
    "category": "general",
    "status": "active",
    "description": "عقد قانوني ملزم",
    "tags": [],
    "companyId": "5",
    "companyName": "شركة ميلانو للأزياء",
    "contractType": "عقد تجاري",
    "parties": [
      "ميلانو"
    ],
    "value": 0
  },
  {
    "id": "doc-1753697814781-a2u5l",
    "name": "اعتماد الشئون ميلانو 20250601.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/اعتماد الشئون ميلانو 20250601.pdf",
    "uploadDate": "2025-07-28T10:16:54.781Z",
    "size": 491252,
    "type": "certification",
    "category": "general",
    "status": "active",
    "description": "اعتماد رسمي من الجهات المختصة",
    "tags": [],
    "companyId": "5",
    "companyName": "شركة ميلانو للأزياء",
    "certificationNumber": "20250601",
    "issuingBody": "الجهة الحكومية المختصة"
  }
];

const allRequestsData = [
  {
    "id": "doc-1753697814797-52zp5",
    "name": "طلب اصدار هوية للمرور.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/طلب اصدار هوية للمرور.docx",
    "uploadDate": "2025-07-28T10:16:54.798Z",
    "size": 125388,
    "type": "request",
    "category": "government",
    "status": "active",
    "description": "طلب رسمي للحصول على خدمة",
    "requestType": "طلب إصدار هوية",
    "submissionDate": null,
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة"
  },
  {
    "id": "doc-1753697814803-c99zg",
    "name": "نموذج هوية 1جوازات.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/نموذج هوية 1جوازات.docx",
    "uploadDate": "2025-07-28T10:16:54.803Z",
    "size": 119817,
    "type": "request",
    "category": "government",
    "status": "active",
    "description": "نموذج رسمي للمعاملات",
    "requestType": "طلب إصدار هوية",
    "submissionDate": null,
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة"
  },
  {
    "id": "doc-1753697814803-uf8ex",
    "name": "نموذج هوية جوازات (2).docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/نموذج هوية جوازات (2).docx",
    "uploadDate": "2025-07-28T10:16:54.803Z",
    "size": 13325,
    "type": "request",
    "category": "government",
    "status": "active",
    "description": "نموذج رسمي للمعاملات",
    "requestType": "طلب إصدار هوية",
    "submissionDate": null,
    "companyId": "1",
    "companyName": "شركة الاتحاد الخليجي للأقمشة"
  },
  {
    "id": "doc-1753697814798-pfc6x",
    "name": "طلب جوازات 2017.pdf",
    "path": "/home/runner/workspace/attached_assets/ملفات/طلب جوازات 2017.pdf",
    "uploadDate": "2025-07-28T10:16:54.798Z",
    "size": 2099236,
    "type": "request",
    "category": "government",
    "status": "active",
    "description": "طلب رسمي للحصول على خدمة",
    "requestType": "طلب خدمات جوازات",
    "submissionDate": "2017-01-01",
    "companyId": "2",
    "companyName": "شركة النيل الأزرق للمجوهرات"
  },
  {
    "id": "doc-1753697814798-9azbs",
    "name": "طلب تقدير احتيلج النيل الزهبي 2024.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/طلب تقدير احتيلج النيل الزهبي 2024.docx",
    "uploadDate": "2025-07-28T10:16:54.798Z",
    "size": 21295,
    "type": "request",
    "category": "government",
    "status": "active",
    "description": "طلب رسمي للحصول على خدمة",
    "requestType": "طلب تقدير احتياج",
    "submissionDate": "2024-01-01",
    "companyId": "3",
    "companyName": "شركة قمة النيل للذهب"
  },
  {
    "id": "doc-1753697814797-vb296",
    "name": "طلب ار جي.docx",
    "path": "/home/runner/workspace/attached_assets/ملفات/طلب ار جي.docx",
    "uploadDate": "2025-07-28T10:16:54.797Z",
    "size": 67675,
    "type": "request",
    "category": "government",
    "status": "active",
    "description": "طلب رسمي للحصول على خدمة",
    "requestType": "طلب خدمة",
    "submissionDate": null,
    "companyId": "4",
    "companyName": "شركة محمد أحمد إبراهيم"
  }
];

const statistics = {
  "totalFiles": 79,
  "totalEmployees": 273,
  "totalLicenses": 9,
  "totalDocuments": 16,
  "totalContracts": 4,
  "totalCertifications": 5,
  "totalRequests": 6
};

export function registerComprehensiveRoutes(app: Express) {
  // Companies with real counts
  app.get("/api/companies", (req, res) => {
    res.json(allCompaniesData);
  });
  
  // All employees
  app.get("/api/employees", (req, res) => {
    res.json(allEmployeesData);
  });
  
  // Company employees
  app.get("/api/companies/:id/employees", (req, res) => {
    const companyId = req.params.id;
    const employees = allEmployeesData.filter(emp => emp.companyId === companyId);
    res.json(employees);
  });
  
  // All licenses
  app.get("/api/licenses", (req, res) => {
    res.json(allLicensesData);
  });
  
  // Company licenses
  app.get("/api/companies/:id/licenses", (req, res) => {
    const companyId = req.params.id;
    const licenses = allLicensesData.filter(lic => lic.companyId === companyId);
    res.json(licenses);
  });
  
  // All documents
  app.get("/api/documents", (req, res) => {
    res.json(allDocumentsData);
  });
  
  // Company documents
  app.get("/api/companies/:id/documents", (req, res) => {
    const companyId = req.params.id;
    const documents = allDocumentsData.filter(doc => doc.companyId === companyId);
    res.json(documents);
  });
  
  // All requests
  app.get("/api/requests", (req, res) => {
    res.json(allRequestsData);
  });
  
  // Company requests
  app.get("/api/companies/:id/requests", (req, res) => {
    const companyId = req.params.id;
    const requests = allRequestsData.filter(req => req.companyId === companyId);
    res.json(requests);
  });
  
  // Statistics
  app.get("/api/statistics", (req, res) => {
    res.json(statistics);
  });
}
